CI Persist credential in release job (#27)
I think this is causing the error in pushing releases in CI.

[Failed
action](https://github.com/pyodide/pyodide-build-environment-nightly/actions/runs/16184361538/job/45691161344)

```
fatal: could not read Username for 'https://github.com/': No such device or address
Error: Process completed with exit code 128.
```

@agriyakhetarpal Could you review this? `persist-credentials: false` was
introduced in #20.

---------

Co-authored-by: Agriya Khetarpal <74401230+agriyakhetarpal@users.noreply.github.com>